### ISSUE TITLE
Image alt tags

### ISSUE THREAD

**Issue by mml1** [IrinaKostevich/codecademy-colmar-academy#1]
Be sure to add a short description in the alt tags for all images. Alt tags with content help users with visual impairments navigate the site easier. 

https://github.com/IrinaKostevich/codecademy-colmar-academy/blob/master/src/index.html

**Comment by IrinaKostevich** [comment]
In the task for Colmar Academy I didn't add any value to alt attribute for those images, that have just 'decoration' role, but don't add any valuable information. Probably, if there was more details, I would add description to the every image. I will take your suggestion into account during the work on my future projects.
