### ISSUE TITLE
index.css

### ISSUE THREAD

**Issue by mml1** [IrinaKostevich/codecademy-colmar-academy#2]
Great work with keeping your code in order and consistent across each css file! A small tip would be to add comments for each section in the index.css file. It seems like you can add a comment noting base, components, and layouts. 

Furthermore, brilliant job labeling the HTML elements. The labels are very descriptive.
https://github.com/IrinaKostevich/codecademy-colmar-academy/blob/master/src/styles/index.css

**Comment by IrinaKostevich** [comment]
Comments are added.
